### ISSUE TITLE
How can I get a beautiful visualization like figure 3 in your paper? I only got a graph of the curves. thanks!

### ISSUE THREAD

**Issue by njnj0314** [riccardomarin/Diff-FMAPs-PyTorch#1]
How can I get a beautiful visualization like figure 3 in your paper? I only got a graph of the curves. thanks!

**Comment by riccardomarin** [comment]
Hi @njnj0314 , I am glad that you solved the first issue.

For the figures, in general, we use this toolbox:
https://github.com/HTDerekLiu/BlenderToolbox

For this paper, if I remember correctly, we used this one that is in MATLAB:
https://github.com/llorz/MatlabRenderToolbox

Best,
Riccardo
