### ISSUE TITLE
  Hello, if I want to use my own grid dataset, how can I convert them into a point cloud dataset similar to the one used in your paper?

### ISSUE THREAD

**Issue by njnj0314** [riccardomarin/Diff-FMAPs-PyTorch#2]
Hello, if I want to use my own grid dataset, how can I convert them into a point cloud dataset similar to the one used in your paper?

**Comment by riccardomarin** [comment]
Hi @njnj0314 , thank you for your interest in our work. 
I am not sure to understand your question. If you are using voxel representations, there are algorithms to convert them into an explicit one like mesh or point cloud (e.g., marching cubes)
